# Jekyll configuration

url: "https://trino.io"

description: >-
  Trino is a high performance, distributed SQL query engine for big data.

twitter:
  username: trinodb

collections:
  posts:
    permalink: /blog/:year/:month/:day/:title.html
  episodes:
    output: true

exclude:
  - ".gitignore"
  - "Gemf*"
  - "README.md"

# Custom variables

trino_version: 403
conduct_email: conduct@trino.io
slack_join: "https://join.slack.com/t/trinodb/shared_invite/zt-1j3qvwwic-BLSS9W16VQXOdwp5gi6p~A"
slack_fqdn: trinodb.slack.com
github_org_url: "https://github.com/trinodb"
github_repo_url: "https://github.com/trinodb/trino"
google_analytics: UA-133457846-1
google_audience: AW-1036784065
linkedin_audience: 2842796
twitter_user: trinodb
twitter_hashtag: trinodb
youtube_channel: trinodb
