# Jekyll configuration

url: "https://trino.io"

description: >-
  Trino is a high performance, distributed SQL query engine for big data.

twitter:
  username: trinodb

collections:
  posts:
    permalink: /blog/:year/:month/:day/:title.html
  episodes:
    output: true

exclude:
  - ".gitignore"
  - "Gemf*"
  - "README.md"

# Custom variables

trino_version: 432
conduct_email: conduct@trino.io
slack_join: "https://join.slack.com/t/trinodb/shared_invite/zt-26c2w5zhf-1d147_5tPzKlS9NqM~6r8w"
slack_fqdn: trinodb.slack.com
github_org_url: "https://github.com/trinodb"
github_repo_url: "https://github.com/trinodb/trino"
google_ga4: G-RJ94STKPJ5
google_ua: UA-133457846-1
google_audience: AW-1036784065
linkedin_audience: 2842796
twitter_user: trinodb
twitter_hashtag: trinodb
youtube_channel: trinodb

paginate: 12 # Number of blog posts per page
paginate_path: "/blog/:num"
