presto_version: 344

google_analytics: UA-133457846-1

slack_url: "https://join.slack.com/t/prestosql/shared_invite/zt-h88upx5f-gVb8XUu16W_jo4I2Cw8ijA"

url: "https://prestosql.io"
description: >-
  Presto is a high performance, distributed SQL query engine for big data.

twitter:
  username: prestosql
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: /assets/presto-og.png

collections:
  posts:
    permalink: /blog/:year/:month/:day/:title.html

exclude:
  - ".gitignore"
  - "Gemf*"
  - "README.md"
