[build]
  command = "jekyll build"
  publish = "_site"

[context.production.environment]
  JEKYLL_ENV = "production"

[[redirects]]
  from = "/blog/assets/*"
  to = "/assets/blog/:splat"

[[redirects]]
  from = "/docs"
  to = "/docs/current/"

[[redirects]]
  from = "/docs/current"
  to = "/docs/current/"

[[redirects]]
  from = "/docs/*"
  to = "https://trinodb.github.io/docs.trino.io/:splat"
  status = 200

[[redirects]]
  from = "/star"
  to = "https://github.com/trinodb/trino/blob/master/.github/star.png"

[[redirects]]
  from = "/presto-the-definitive-guide"
  to = "/trino-the-definitive-guide"

[[redirects]]
  from = "/presto-the-definitive-guide.html"
  to = "/trino-the-definitive-guide.html"
